services:

  vite-app:
    build:
      context: ./vite-app
      args:
        REPO_URL: "https://github.com/SynerVol/WebPage.git"
    depends_on:
      - python-back
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - drone-net

  python-back:
    build:
      context: ./python-back
      args:
        REPO_URL: https://github.com/SynerVol/MiddleWare.git
    environment:
      - LEADER_PORT='tcp:192.168.1.23:5763'
      - FOLLOWER_PORT='tcp:192.168.1.23:5773'
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - drone-net

  mavproxy:
    build:
      context: ./mavproxy
      args:
        REPO_URL: https://github.com/SynerVol/Simulation_MavProxy.git
    devices:
      - "/dev/ttyACM0:/dev/video_drone"
    user: root
    ports:
      - "14550:14550/udp"
      - "14551:14551/udp"
    restart: unless-stopped
    command: >
      python /usr/local/bin/mavproxy.py
      --master=/dev/video_drone
      --baudrate 115200
      --out udpin:0.0.0.0:14550
      --out udpin:0.0.0.0:14551
      --daemon
      --nowait
      --non-interactive
    networks:
      - drone-net
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0  # if using serial, adjust as needed

  ai-app:
    build:
      context: ./ai-app
      args:
        REPO_URL: https://github.com/SynerVol/yolo_drone.git
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - drone-net
    volumes:
      - ./screenshots:/tmp
    devices:
      - "/dev/video0:/dev/video0"
    group_add:
      - video
    stdin_open: true
    tty: true

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - drone-net

networks:
  drone-net:
    driver: bridge

